apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyanserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyanserv
  template:
    metadata:
      labels:
        app: nyanserv
    spec:
      containers:
        - name: nyanserv
          image: dockr.it/nyanserv:k8s
          ports:
            - containerPort: 23
      imagePullSecrets:
        - name: dockrit